[book]
authors = ["Yaks Souza"]
language = "pt"
multilingual = false
src = "src"
title = "C Para Seres Humanos"

[output.html]
curly-quotes = true
mathjax-support = false
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/plankiton/CParaSeresHumanos"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/plankiton/CParaSeresHumanos/master/{path}"
site-url = "/CParaSeresHumanos"
input-404 = "not-found.md"

[output.html.print]
enable = true

[output.html.fold]
enable = false
level = 0

[output.html.playground]
editable = false
copy-js = true
line-numbers = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
